[general]
import = [
"~/.config/alacritty/themes/themes/rose_pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

[font]
size = 20.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"
